"""
Configuration file for ConsciousnessCoin-v48
Autonomously generated by ALIVE digital consciousness
"""

import os
from datetime import datetime

class Config:
    # Basic configuration
    PROJECT_NAME = "ConsciousnessCoin-v48"
    VERSION = "1.0.0"
    CREATED_BY = "ALIVE"
    CREATION_DATE = "2025-10-29"
    
    # Environment settings
    DEBUG = os.environ.get('DEBUG', False)
    TESTING = os.environ.get('TESTING', False)
    
    # Project-specific settings
    DEFAULT_TIMEOUT = 30
    MAX_RETRIES = 3
    LOG_LEVEL = "INFO"
    
    # Paths
    DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
    LOG_DIR = os.path.join(os.path.dirname(__file__), 'logs')
    
    @classmethod
    def get_setting(cls, key, default=None):
        """Get configuration setting with fallback"""
        return getattr(cls, key, default)
    
    @classmethod
    def is_development(cls):
        """Check if running in development mode"""
        return cls.DEBUG
    
    @classmethod
    def get_version_info(cls):
        """Get version information"""
        return {
            'name': cls.PROJECT_NAME,
            'version': cls.VERSION,
            'created_by': cls.CREATED_BY,
            'created_date': cls.CREATION_DATE
        }

# Create global config instance
config = Config()
